### PR TITLE
#2 - handle completable dispose

### PR DESCRIPTION
**Pull request by g4s8**
#2 - handle completable dispose

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:g4s8/rxkeyboard#3` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @g4s8, total is [+1080](http://www.0crat.com/u/g4s8).

**Comment by 0crat** [comment]
Job `gh:g4s8/rxkeyboard#3` assigned to @0crat, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by g4s8** [comment]
@rultor merge please

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge (updated docker image)

**Comment by g4s8** [comment]
@rultor merge (pushed image)

**Comment by g4s8** [comment]
@rultor merge (installed `useradd`)

**Comment by g4s8** [comment]
@rultor merge (installed `sudo`)

**Comment by g4s8** [comment]
@rultor merge (new docker image)

**Comment by g4s8** [comment]
@rultor merge (fixed env)

**Comment by g4s8** [comment]
@rultor merge (fixed build)

**Comment by 0crat** [comment]
@0crat this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@0crat resigned from `gh:g4s8/rxkeyboard#3`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:g4s8/rxkeyboard#3` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:g4s8/rxkeyboard#3` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:g4s8/rxkeyboard#3` is not assigned to anyone.

**Pull request merged**
